### PR TITLE
jira_bot.py: implement github to jira syntax

### PR DESCRIPTION
**Pull request by schuellerf**
Github allows for html mixed with other syntax,
for now we handle some common html syntax to
get converted to jira syntax.

### CODE REVIEW

**Comment by ochosi** [comment]
Is there an easy way to test this?

**Comment by schuellerf** [comment]
well, there are tests but you would need to link an issue with codecov syntax to jira
(or copy a raw message from codecov like https://github.com/osbuild/image-builder-frontend/pull/2683 into a test PR) and do the `/jira-epic …" command then)
but we would need to merge it to staging first anyway, I guess :-/

**Comment by ochosi** [comment]
Locally tested this with `pytest`:

```
pytest test_gh_to_jira.py 
================================================== test session starts ===================================================
platform linux -- Python 3.13.0, pytest-8.3.4, pluggy-1.5.0
rootdir: /home/ssteinbe/dev/pr-best-practices
collected 7 items                                                                                                        

test_gh_to_jira.py .......                                                                                         [100%]

=================================================== 7 passed in 0.07s ====================================================
```

**Pull request merged**
